# -*- coding: utf-8 -*-
"""code_a_pookalam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZMY--QcIUfzkwiDjPMzDuXzBTcHeb-ay

Install Joy,This installs the Joy library we'll use to draw shapes
"""

pip install python-joy

"""Import Joy
Run this next — it loads all the drawing tools (circle, square, move, repeat, etc.)
"""

from joy import *

RED = "#A71930"
DARK_RED = "#6E1424"
YELLOW = "#FFD21F"
GOLD = "#F5A900"
ORANGE = "#F47C20"
DARK_ORANGE = "#D94B16"
GREEN = "#315C2B"
DARK_GREEN = "#193D22"
WHITE = "#FFFFFF"
CREAM = "#F5E7C1"
BROWN = "#6B321F"

background=rectangle(w=300,h=300,fill=WHITE)
show(background)

p1 = circle(x=0,y=4,r=2,fill=RED,stroke="none")
p2 = circle(x=3,y=1,r=2,fill=RED,stroke="none")
p3 = circle(x=2,y=-3,r=2,fill=RED,stroke="none")
p4 = circle(x=-2,y=-3,r=2,fill=RED,stroke="none")
p5 = circle(x=-3,y=1,r=2,fill=RED,stroke="none")
center = circle(x=0,y=0,r=1.8,fill=YELLOW,stroke="none")
flower = p1+p2+p3+p4+p5+center
flowers = flower|translate(y=140)|repeat(18,rotate(20))
show(background,flowers)

p1 = circle(x=0,y=4,r=2,fill=YELLOW,stroke="none")
p2 = circle(x=3,y=1,r=2,fill=YELLOW,stroke="none")
p3 = circle(x=2,y=-3,r=2,fill=YELLOW,stroke="none")
p4 = circle(x=-2,y=-3,r=2,fill=YELLOW,stroke="none")
p5 = circle(x=-3,y=1,r=2,fill=YELLOW,stroke="none")
center = circle(x=0,y=0,r=1.8,fill=ORANGE,stroke="none")
flower = p1+p2+p3+p4+p5+center
yellowflower = flower|translate(y=140)|rotate(5)
yellowflowers = yellowflower|repeat(72,rotate(5))
show(background,yellowflowers,flowers)

greenCircle = circle(x=0,y=0,r=145,fill=GREEN,stroke="none")
show(background,greenCircle,creamCircle,yellowflowers,flowers)

creamCircle = circle(x=0,y=0,r=135,fill=CREAM,stroke="none")

show(background,greenCircle,creamCircle,yellowflowers,flowers)

p1 = point(x=-8,y=130)
p2 = point(x=8,y=130)
p3 = point(x=0,y=75)
yellowTriangle = polygon([p1,p2,p3],fill=YELLOW,stroke="none")
yellowTriangles = yellowTriangle|repeat(18,rotate(20))
show(background,greenCircle,creamCircle,yellowTriangles,yellowflowers,flowers)

p4 = point(x=-12,y=130)
p5 = point(x=-6,y=130)
p6 = point(x=0,y=75)
orangeLeft = polygon([p4,p5,p6],fill=ORANGE,stroke="none")
p7 = point(x=0,y=75)
p8 = point(x=6,y=130)
p9 = point(x=12,y=130)
orangeRight = polygon([p7,p8,p9],fill=ORANGE,stroke="none")
orangeTrianglesLeft = orangeLeft|repeat(18,rotate(20))
orangeTrianglesRight = orangeRight|repeat(18,rotate(20))
show(background,greenCircle,creamCircle,orangeTrianglesLeft,yellowTriangles,orangeTrianglesRight,yellowflowers,flowers)

p10 = point(x=-18,y=130)
p11 = point(x=-12,y=130)
p12 = point(x=0,y=75)
redLeft = polygon([p10,p11,p12],fill=RED,stroke="none")
p13 = point(x=0,y=75)
p14 = point(x=12,y=130)
p15 = point(x=18,y=130)
redRight = polygon([p13,p14,p15],fill=RED,stroke="none")
redLeftTriangles = redLeft|repeat(18,rotate(20))
redRightTriangles = redRight|repeat(18,rotate(20))
show(background,greenCircle,creamCircle,redLeftTriangles,orangeTrianglesLeft,yellowTriangles,orangeTrianglesRight,redRightTriangles,yellowflowers,flowers)

line1 = line(x1=0,y1=75,x2=0,y2=130,stroke=WHITE,strokeWidth=4)
lines = line1|repeat(18,rotate(20))
show(background,greenCircle,creamCircle,redLeftTriangles,orangeTrianglesLeft,yellowTriangles,orangeTrianglesRight,redRightTriangles,lines,yellowflowers,flowers)

p16 = point(x=-24,y=130)
p17 = point(x=-18,y=130)
p18 = point(x=0,y=75)
brownLeft = polygon([p16,p17,p18],fill=BROWN,stroke="none")
p19 = point(x=0,y=75)
p20 = point(x=18,y=130)
p21 = point(x=24,y=130)
brownRight = polygon([p19,p20,p21],fill=BROWN,stroke="none")
brownTrianglesLeft = brownLeft|repeat(18,rotate(20))
brownTrianglesRight = brownRight|repeat(18,rotate(20))
show(background,greenCircle,creamCircle,brownTrianglesLeft,redLeftTriangles,orangeTrianglesLeft,yellowTriangles,orangeTrianglesRight,redRightTriangles,brownTrianglesRight,yellowflowers,flowers)

def flower_border():
    layer1 = circle(y=100, r=18, fill=BROWN, stroke="none")
    layer2 = circle(y=98, r=16, fill=RED, stroke="none")
    layer3 = circle(y=96, r=14, fill=ORANGE, stroke="none")
    layer4 = circle(y=94, r=12, fill=YELLOW, stroke="none")
    return layer1 + layer2 + layer3 + layer4
outer_layer = flower_border() | repeat(18, rotate(20))
yellowcircle3= circle(x=0,y=0,r=98,fill=YELLOW,stroke="none")
show(background,greenCircle,creamCircle,brownTrianglesLeft,redLeftTriangles,orangeTrianglesLeft,yellowTriangles,orangeTrianglesRight,redRightTriangles,brownTrianglesRight,yellowflowers,flowers,outer_layer,yellowcircle3)



yellow1 = rectangle(x=-15, y=90,w=10, h=10,fill=RED,stroke="none")

orange1 = rectangle(
    x=-5, y=90,
    w=10, h=10,
    fill=ORANGE,
    stroke="none"
)

white1 = rectangle(
    x=5, y=90,
    w=10, h=10,
    fill=WHITE,
    stroke="none"
)

yellow2 = rectangle(
    x=15, y=90,
    w=10, h=10,
    fill=RED,
    stroke="none"
)


yellow45 = yellow1 | rotate(90)  | repeat(16, rotate(22.5))
orange45 = orange1 | rotate(90)  | repeat(16, rotate(22.5))
white45 = white1 | rotate(90)  | repeat(16, rotate(22.5))
yellow45_2 = yellow2 | rotate(90) | repeat(16, rotate(22.5))

smallpatch=yellow45+orange45+white45+yellow45_2
show(
    background,
    greenCircle,
    creamCircle,
    brownTrianglesLeft,
    redLeftTriangles,
    orangeTrianglesLeft,
    yellowTriangles,
    orangeTrianglesRight,
    redRightTriangles,
    brownTrianglesRight,
    yellowflowers,
    flowers,
    outer_layer,yellowcircle3,
  smallpatch
)

center_green = circle(r=88,fill=GREEN,stroke="none")
show(background,
    greenCircle,
    creamCircle,
    brownTrianglesLeft,
    redLeftTriangles,
    orangeTrianglesLeft,
    yellowTriangles,
    orangeTrianglesRight,
    redRightTriangles,
    brownTrianglesRight,
    yellowflowers,
    flowers,
    outer_layer,yellowcircle3,
  smallpatch,center_green)

h1 = point(x=0,   y=82)
h2 = point(x=71,  y=41)
h3 = point(x=71,  y=-41)
h4 = point(x=0,   y=-82)
h5 = point(x=-71, y=-41)
h6 = point(x=-71, y=41)


yellowHexagon = polygon(
    [h1,h2,h3,h4,h5,h6],
    fill=YELLOW,
    stroke="none"
)


show(
    background,
    greenCircle,
    creamCircle,
    brownTrianglesLeft,
    redLeftTriangles,
    orangeTrianglesLeft,
    yellowTriangles,
    orangeTrianglesRight,
    redRightTriangles,
    brownTrianglesRight,
    yellowflowers,
    flowers,
    outer_layer,
    yellowcircle3,
    smallpatch,
    center_green,
    yellowHexagon
)

y1 = point(x=-55, y=45)
y2 = point(x=-38, y=55)
y3 = point(x=0,   y=87)

yellowTri = polygon(
    [y1,y2,y3],
    fill=YELLOW,
    stroke="none"
)

o1 = point(x=-38, y=55)
o2 = point(x=-20, y=65)
o3 = point(x=0,   y=87)

orangeTri = polygon(
    [o1,o2,o3],
    fill=ORANGE,
    stroke="none"
)

r1 = point(x=-20, y=65)
r2 = point(x=-8, y=70)
r3 = point(x=0,  y=87)

redTri = polygon(
    [r1,r2,r3],
    fill=RED,
    stroke="none"
)

b1 = point(x=-8, y=70)
b2 = point(x=0,  y=70)
b3 = point(x=0,  y=87)

brownTri = polygon(
    [b1,b2,b3],
    fill=BROWN,
    stroke="none"
)


yellowTris = yellowTri | repeat(12, rotate(30))
orangeTris = orangeTri | repeat(12, rotate(30))
redTris = redTri | repeat(12, rotate(30))
brownTris = brownTri | repeat(12, rotate(30))
innertris=yellowTris+orangeTris+redTris+brownTris
show(background,
    greenCircle,
    creamCircle,
    brownTrianglesLeft,
    redLeftTriangles,
    orangeTrianglesLeft,
    yellowTriangles,
    orangeTrianglesRight,
    redRightTriangles,
    brownTrianglesRight,
    yellowflowers,
    flowers,
    outer_layer,
    yellowcircle3,
    smallpatch,
    center_green,
    yellowHexagon,
innertris
)

r1=rectangle(w=90,h=50,fill=GOLD,stroke="MAROON") | repeat(72,rotate(20) |scale(0.9))
r2=rectangle(w=50,h=90,fill=GOLD,stroke="MAROON") | repeat(72,rotate(20) |scale(0.9))
r3=rectangle(w=70,h=50,fill=GOLD,stroke="MAROON") | repeat(72,rotate(20) |scale(0.9))
r=r1+r2+r3
show(r)

outter1 = (
    circle(r=75, fill=DARK_RED, stroke="none")
    + circle(r=68, fill=GREEN, stroke="none")
)


lines1 = (
    rectangle(
        y=52,
        w=12,
        h=55,
        fill=DARK_RED,
        stroke="none"
    )
    +
    rectangle(
        y=52,
        w=12,
        h=55,
        fill=DARK_RED,
        stroke="none"
    )
) | repeat(8, rotate(45))


lines2 = (
    rectangle(
        y=52,
        w=12,
        h=55,
        fill=WHITE,
        stroke="none"
    )
    +
    rectangle(
        y=52,
        w=12,
        h=55,
        fill=DARK_RED,
        stroke="none"
    )
) | repeat(8, rotate(45))

octagon1 = polygon(
    [
        point(0,-75),
        point(53,-53),
        point(75,0),
        point(53,53),
        point(0,75),
        point(-53,53),
        point(-75,0),
        point(-53,-53)
    ],
    fill=YELLOW,
    stroke="none"
)

def small_petal():

    outer_p = ellipse(
        y=55,
        w=20,
        h=37,
        fill=DARK_RED,
        stroke="none"
    )

    mid_p = ellipse(
        y=51,
        w=17,
        h=31,
        fill=ORANGE,
        stroke="none"
    )

    inner_p = ellipse(
        y=48,
        w=14,
        h=24,
        fill=YELLOW,
        stroke="none"
    )

    core_p = ellipse(
        y=44,
        w=9,
        h=17,
        fill=YELLOW,
        stroke="none"
    )

    return outer_p + mid_p + inner_p + core_p

small = (
    small_petal()
    | rotate(25)
    | repeat(8, rotate(45))
)
center_dot = (
    circle(
        r=20,
        fill=YELLOW,
        stroke="none"
    )
    +
    circle(
        r=8,
        fill=DARK_RED,
        stroke="none"
    )
)-
middle = (
    outter1
    + octagon1
    + small
    + lines1
    + lines2
    + center_dot
)
show(background,
    greenCircle,
    creamCircle,
    brownTrianglesLeft,
    redLeftTriangles,
    orangeTrianglesLeft,
    yellowTriangles,
    orangeTrianglesRight,
    redRightTriangles,
    brownTrianglesRight,
    yellowflowers,
    flowers,
    outer_layer,
    yellowcircle3,
    smallpatch,
    center_green,
    yellowHexagon,
innertris
,middle,r)

outter2 = (circle(r=22, fill=DARK_RED, stroke="none")+ circle(r=20, fill=GREEN, stroke="none"))
lines12 = (rectangle(y=15,w=5,h=16,fill=DARK_RED,stroke="none")
    +rectangle(y=15,w=5,h=16,fill=DARK_RED,stroke="none")) | repeat(8, rotate(45))
lines22 = (rectangle(y=15,w=5,h=16,fill=WHITE,stroke="none")  +
           rectangle(y=15,w=5,h=16,fill=DARK_RED,stroke="none")) | repeat(8, rotate(45))
octagon2 = polygon([point(0, -22),
        point(16, -16),
        point(22, 0),
        point(16, 16),
        point(0, 22),
        point(-16, 16),
        point(-22, 0),
        point(-16, -16)],fill=WHITE,stroke="none")
def small_petal():
outer_p2 = ellipse(y=16,w=6,h=11,fill=DARK_RED,stroke="none")
mid_p2 = ellipse(y=15,w=5,h=9,fill=ORANGE,stroke="none")
inner_p2 = ellipse(y=14,w=4,h=7,fill=YELLOW,stroke="none")
core_p2 = ellipse(y=13,w=2.5,h=5,fill=WHITE,stroke="none")
return outer_p2 + mid_p2 + inner_p2 + core_p2
small2 = (small_petal()| rotate(25)| repeat(8, rotate(45)))
center_dot2 = (circle(r=6,fill=YELLOW,stroke="none")+circle(r=2.5,fill=DARK_RED,stroke="none"))
middle12 = (outter2+ octagon2+ small2+ lines12+ lines22+ center_dot2)
middle12 = middle1 | scale(1.5)
show(background,greenCircle,creamCircle,brownTrianglesLeft,redLeftTriangles,orangeTrianglesLeft,yellowTriangles,orangeTrianglesRight,redRightTriangles,brownTrianglesRight,yellowflowers,flowers,outer_layer,yellowcircle3,smallpatch,center_green,yellowHexagon,innertris,middle,r,middle1)

